const fs = require('fs');
const path = 'C:/Users/kexuc/.openclaw/workspace/professional_quant_platform/frontend/src/pages/Portfolio.tsx';
let l = fs.readFileSync(path, 'utf8').split('\n');
console.log('Starting from clean v1.8.5, lines:', l.length);

// ============================
// 1. MTF + Backtest columns config (columns array, before Priority column)
// ============================
// Find the columns array — look for 'Priority' column title  
const priorityCol = l.findIndex(x => x.indexOf("title: 'Priority'") >= 0);
console.log('Priority column at', (priorityCol+1));

// Insert new columns BEFORE Priority column
const newColumns = [
  "    {",
  "      title: 'MTF Alignment',",
  "      key: 'mtfAlignment',",
  "      width: 150,",
  "      render: (record: any) => {",
  "        const mtf = record.mtf || {};",
  "        if (!mtf.alignment) return <span style={{color:'#999',fontSize:'11px'}}>--</span>;",
  "        let color = '#52c41a';",
  "        if (mtf.alignment.indexOf('Conflicted') >= 0) color = '#ff4d4f';",
  "        else if (mtf.alignment.indexOf('Partially') >= 0) color = '#faad14';",
  "        else if (mtf.alignment.indexOf('bearish') >= 0) color = '#ff4d4f';",
  "        return (",
  "          <div>",
  "            <Tag color={color} style={{fontSize:'10px',marginBottom:0}}>{mtf.alignment}</Tag>",
  "            <div style={{fontSize:'10px',color:'#888',marginTop:2}}>{mtf.mtfNotes?.substring(0,50) || ''}</div>",
  "          </div>",
  "        );",
  "      },",
  "    },",
  "    {",
  "      title: 'Daily',",
  "      key: 'dailyBias',",
  "      width: 90,",
  "      render: (record: any) => {",
  "        const mtf = record.mtf || {};",
  "        return <span style={{fontSize:'11px',color:'#666'}}>{mtf.dailyBias || '--'}</span>;",
  "      },",
  "    },",
  "    {",
  "      title: '4H/1H',",
  "      key: 'midBias',",
  "      width: 80,",
  "      render: (record: any) => {",
  "        const mtf = record.mtf || {};",
  "        return <span style={{fontSize:'11px',color:'#666'}}>{mtf.midBias || '--'}</span>;",
  "      },",
  "    },",
  "    {",
  "      title: 'Entry',",
  "      key: 'entryTiming',",
  "      width: 80,",
  "      render: (record: any) => {",
  "        const mtf = record.mtf || {};",
  "        let color = '#52c41a';",
  "        if (mtf.entryTiming === 'Extended') color = '#ff4d4f';",
  "        else if (mtf.entryTiming === 'Stable') color = '#1890ff';",
  "        return <Tag color={color} style={{fontSize:'10px',marginBottom:0}}>{mtf.entryTiming || '--'}</Tag>;",
  "      },",
  "    },",
  "    {",
  "      title: 'Backtest Check',",
  "      key: 'backtestCheck',",
  "      width: 110,",
  "      render: (record: any) => {",
  "        const bt = record.backtest || {};",
  '        const status = bt.status || "Pending";',
  "        let color = '#8c8c8c';",
  "        let shortMsg = '';",
  "        if (status === 'Passed') { color = '#52c41a'; shortMsg = 'Stable'; }",
  "        else if (status === 'Caution') {",
  "          color = '#faad14';",
  "          shortMsg = bt.summary && bt.summary.length < 30 ? bt.summary : 'Review needed';",
  "        }",
  "        else if (status === 'Failed') {",
  "          color = '#ff4d4f';",
  "          shortMsg = bt.summary && bt.summary.length < 30 ? bt.summary : 'Unusable';",
  "        }",
  "        else if (status === 'Skipped') {",
  "          color = '#d9d9d9';",
  "          shortMsg = bt.summary && bt.summary.length < 30 ? bt.summary : 'Skipped';",
  "        }",
  "        else if (status === 'Error') {",
  "          color = '#8c8c8c';",
  "          const errType = bt.errorClassification || 'unknown';",
  "          if (errType === 'strategy_not_mapped') shortMsg = 'Strategy';",
  "          else if (errType === 'api_failed_or_empty') shortMsg = 'API';",
  "          else shortMsg = 'No data';",
  "        }",
  "        return (",
  "          <div>",
  "            <Tag color={color} style={{ fontSize: '10px', marginBottom: 0 }}>{status}</Tag>",
  '            <div style={{ fontSize: \'10px\', color: \'#888\', marginTop: 2 }}>{shortMsg}</div>',
  "          </div>",
  "        );",
  "      },",
  "    },",
  "    {",
  "      title: 'Conclusion',",
  "      key: 'conclusion',",
  "      width: 90,",
  "      render: (record: any) => {",
  "        const conclusion = record.conclusion || (record.priorityScore >= 70 ? 'Proceed' : record.priorityScore >= 40 ? 'Watch' : 'Skip');",
  "        const color = record.conclusionColor || (conclusion === 'Proceed' ? '#52c41a' : conclusion === 'Watch' ? '#faad14' : '#ff4d4f');",
  "        return (",
  "          <div>",
  "            <Badge color={color} text={<span style={{fontSize:'11px',fontWeight:600,color}}>{conclusion}</span>} />",
  "            <div style={{fontSize:'10px',color:'#888',marginTop:2}}>Score: {record.priorityScore || record.matchConfidence || '--'}</div>",
  "          </div>",
  "        );",
  "      },",
  "    },",
];

// The original has:
//     },
//   ];
// at priorityCol+1
l.splice(priorityCol + 1, 0, ...newColumns);
console.log('Inserted new columns before Priority. Lines:', l.length);

// ============================
// 2. analyzeMultiTimeframe function (before handleRunFineScan)
// ============================
const handleFn = l.findIndex(x => x.indexOf("const handleRunFineScan") >= 0);

const analyzeMtf = [
  "",
  "// MTF analysis: derive multi-timeframe alignment from scanner fields",
  "const analyzeMultiTimeframe = (candidate: any): { alignment: string; dailyBias: string; midBias: string; entryTiming: string; midStructure: string; mtfNotes: string; } => {",
  "  const trendLabel = candidate.trendLabel || candidate.trend || 'Neutral';",
  "  const score = candidate.overallScore || candidate.trendScore || 0;",
  "  const volumeStatus = candidate.volumeStatus || 'Normal';",
  "  const risk = candidate.eventRisk || 'Medium';",
  "  const momentumLabel = candidate.momentumLabel || '';",
  "  const volatilityLabel = candidate.volatilityLabel || '';",
  "  const structureLabel = candidate.structureLabel || '';",
  "  const priceChange = candidate.changePct || candidate.priceChangePct || 0;",
  "",
  "  // Layer 1: DAILY (main trend)",
  "  let dailyBias = 'Neutral';",
  "  if (trendLabel === 'Strong Bullish') dailyBias = 'Strong Bullish';",
  "  else if (trendLabel === 'Bullish') dailyBias = 'Bullish';",
  "  else if (trendLabel === 'Bearish') dailyBias = 'Bearish';",
  "  else if (trendLabel === 'Strong Bearish') dailyBias = 'Strong Bearish';",
  "",
  "  // Layer 2: MID STRUCTURE (4H/1H proxy)",
  "  let midSignals = 0;",
  "  if (momentumLabel === 'strengthening' || momentumLabel === 'improving') midSignals++;",
  "  if (structureLabel === 'uptrend' || structureLabel === 'breakout') midSignals++;",
  "  if (structureLabel === 'pullback' || structureLabel === 'consolidating') midSignals--;",
  "  if (volumeStatus === 'High' || volumeStatus === 'Increasing') midSignals++;",
  "  if (score >= 75) midSignals += 1;",
  "",
  "  let midStructure = 'Mixed';",
  "  let midBias = 'Neutral';",
  "  if (midSignals >= 4) { midStructure = 'Strong'; midBias = 'Bullish'; }",
  "  else if (midSignals >= 2) { midStructure = 'Mixed'; midBias = dailyBias.indexOf('Bullish') >= 0 ? 'Slightly Bullish' : dailyBias.indexOf('Bearish') >= 0 ? 'Slightly Bearish' : 'Neutral'; }",
  "  else if (midSignals <= 0) { midStructure = 'Weak'; midBias = 'Bearish'; }",
  "  else { midStructure = 'Weak'; midBias = dailyBias.indexOf('Bullish') >= 0 ? 'Neutral' : 'Bearish'; }",
  "",
  "  // Layer 3: ENTRY TIMING (15m/30m proxy)",
  "  let entryTiming = 'Normal';",
  "  if (Math.abs(priceChange) > 5) entryTiming = 'Extended';",
  "  else if (Math.abs(priceChange) < 1 && trendLabel.indexOf('Bullish') >= 0) entryTiming = 'Stable';",
  "  else if (volatilityLabel === 'Low') entryTiming = 'Stable';",
  "  else if (volatilityLabel === 'High' && Math.abs(priceChange) > 3) entryTiming = 'Extended';",
  "",
  "  // Overall alignment",
  "  let alignment = 'Conflicted';",
  "  const isBullish = dailyBias.indexOf('Bullish') >= 0;",
  "  const isBearish = dailyBias.indexOf('Bearish') >= 0;",
  "  if (isBullish && midBias === 'Bullish') alignment = 'Aligned';",
  "  else if (isBullish && (midBias === 'Slightly Bullish' || midBias === 'Neutral')) alignment = 'Partially aligned';",
  "  else if (isBearish && midBias === 'Bearish') alignment = 'Aligned (bearish)';",
  "  else if (isBearish && (midBias === 'Slightly Bearish' || midBias === 'Neutral')) alignment = 'Partially aligned';",
  "",
  "  const mtfNotes = alignment === 'Aligned' ? 'Strong multi-timeframe support' :",
  "    alignment === 'Partially aligned' ? 'Caution: mid-term divergence from daily trend' :",
  "    alignment === 'Aligned (bearish)' ? 'Bearish alignment across timeframes' :",
  "    'Conflicting signals across timeframes';",
  "",
  "  return { alignment, dailyBias, midBias, entryTiming, midStructure, mtfNotes };",
  "};",
];

l.splice(handleFn, 0, ...analyzeMtf);
console.log('Inserted analyzeMultiTimeframe. Lines:', l.length);

// ============================
// 3. runQuickBacktest (NEW version with strategy support check + all strategies + details)
// ============================
// Find where to insert — after analyzeMultiTimeframe and before handleRunFineScan
// The start of handleRunFineScan shifted due to insert above
const newHandleFn = l.findIndex(x => x.indexOf("const handleRunFineScan") >= 0);

const runQuickBt = [
  "",
  "// Quick backtest: for each strategy, check support, run if supported, collect all results",
  "const runQuickBacktest = async (symbol: string, strategies: string[]): Promise<any> => {",
  "  // Backtest page supported strategies (matching Backtest.tsx line 1148-1152)",
  "  // Only these strategies have backend endpoints",
  "  const supportedByBacktest: Record<string, string> = {",
  "    'Moving Average':  'moving_average',",
  "    'MACD':            'macd',",
  "    'RSI':             'rsi',",
  "    'Bollinger Band':  'bollinger',",
  "    'Momentum Continuation': 'momentum',",
  "  };",
  "",
  "  // Strategy display aliases: Fine Scan may match names that differ from Backtest.tsx labels",
  "  const strategyDisplayAlias: Record<string, string> = {",
  "    'Moving Average Crossover': 'Moving Average',",
  "    'Moving Average': 'Moving Average',",
  "  };",
  "",
  "  if (!strategies || strategies.length === 0) {",
  "    return {",
  "      status: 'Skipped', bestStrategy: 'None',",
  "      totalReturn: 0, sharpe: 0, maxDrawdown: 0, winRate: 0, profitFactor: 0, tradeCount: 0, recentValid: false,",
  "      summary: 'No strategy to backtest',",
  "      details: []",
  "    };",
  "  }",
  "",
  "  const endDate = new Date();",
  "  const start3M = new Date(); start3M.setMonth(start3M.getMonth() - 3);",
  "  const start6M = new Date(); start6M.setMonth(start6M.getMonth() - 6);",
  "  const start1Y = new Date(); start1Y.setFullYear(start1Y.getFullYear() - 1);",
  "  const fmt = (d: Date) => d.toISOString().split('T')[0];",
  "",
  "  // Helper: call backtest API for one strategy with one window",
  "  const tryWindow = async (backendKey: string, params: any, start: Date): Promise<any> => {",
  "    try {",
  "      const config: any = {",
  "        strategy: backendKey,",
  "        symbol: symbol,",
  "        symbols: [symbol],",
  "        startDate: fmt(start),",
  "        endDate: fmt(endDate),",
  "        initialCapital: 10000,",
  "        dataMode: 'real',",
  "        parameters: params || {},",
  "      };",
  "      const response = await backtraderAPI.runBacktest(config);",
  "      let resultData = response.data;",
  "      if (resultData?.result?.results) resultData = resultData.result.results;",
  "      if (resultData?.results) resultData = resultData.results;",
  "",
  "      return {",
  "        totalReturn: typeof resultData?.totalReturn === 'number' ? resultData.totalReturn : 0,",
  "        sharpe:   typeof resultData?.sharpeRatio === 'number' ? resultData.sharpeRatio : (resultData?.sharpe || 0),",
  "        maxDrawdown: typeof resultData?.maxDrawdown === 'number' ? resultData.maxDrawdown : 0,",
  "        winRate: typeof resultData?.winRate === 'number' ? resultData.winRate : 0,",
  "        profitFactor: typeof resultData?.profitFactor === 'number' ? resultData.profitFactor : 0,",
  "        tradeCount: (resultData?.tradesList || []).length,",
  "      };",
  "    } catch (e) {",
  "      console.warn('[QUICK BT] Failed for ' + symbol + ' ' + backendKey + ': ' + (e as any).message);",
  "      return null;",
  "    }",
  "  };",
  "",
  "  // Parameters for each strategy (matching Backtest.tsx strategy config)",
  "  const strategyParams: Record<string, any> = {",
  "    'moving_average': { shortMaPeriod: 10, longMaPeriod: 30 },",
  "    'rsi':            { rsiPeriod: 14, rsiOversold: 30, rsiOverbought: 70 },",
  "    'macd':           { macdFast: 12, macdSlow: 26, macdSignal: 9 },",
  "    'bollinger':      { bollingerPeriod: 20, bollingerStdDev: 2 },",
  "    'momentum':       { momentumPeriod: 10 },",
  "  };",
  "",
  "  // Process ALL strategies — supported ones run, unsupported ones get status 'Skipped'",
  "  const allDetails: any[] = [];",
  "  let bestResult: any = null;",
  "  let bestStrategyName = '';",
  "",
  "  for (const s of strategies) {",
  "    // Check if this strategy is supported by the backtest engine",
  "    const resolvedName = strategyDisplayAlias[s] || s;",
  "    const backendKey = supportedByBacktest[resolvedName];",
  "    if (!backendKey) {",
  "      allDetails.push({",
  "        strategyName: s, status: 'Skipped',",
  "        reason: 'Strategy not supported in Backtest',",
  "        totalReturn: null, sharpe: null, maxDrawdown: null, winRate: null, profitFactor: null, tradeCount: null, windowUsed: null,",
  "      });",
  "      continue;",
  "    }",
  "",
  "    const params = strategyParams[backendKey] || {};",
  "",
  "    // Try 3M first, then 6M, then 1Y (sequential within strategy)",
  "    let result = await tryWindow(backendKey, params, start3M);",
  "    let windowUsed = '3M';",
  "    if (result && result.tradeCount < 5) {",
  "      const r6m = await tryWindow(backendKey, params, start6M);",
  "      if (r6m && r6m.tradeCount > (result?.tradeCount || 0)) { result = r6m; windowUsed = '6M'; }",
  "    }",
  "    if (result && result.tradeCount < 5) {",
  "      const r1y = await tryWindow(backendKey, params, start1Y);",
  "      if (r1y && r1y.tradeCount > (result?.tradeCount || 0)) { result = r1y; windowUsed = '1Y'; }",
  "    }",
  "",
  "    if (result && result.tradeCount > 0) {",
  "      // Evaluation (stability-first)",
  "      let st = 'Caution';",
  "      const tc = result.tradeCount;",
  "      const tr = result.totalReturn;",
  "      const dd = result.maxDrawdown;",
  "      const sr = result.sharpe;",
  "      const pf = result.profitFactor;",
  "      if (tc < 3) st = 'Failed';",
  "      else if (tr < -5) st = 'Failed';",
  "      else if (dd > 30) st = 'Caution';",
  "      else if (sr < 0.5 && tc < 10) st = 'Caution';",
  "      else if (pf < 0.8 && tc < 15) st = 'Caution';",
  "      else st = 'Passed';",
  "",
  "      allDetails.push({",
  "        strategyName: s, status: st, windowUsed: windowUsed,",
  "        totalReturn: result.totalReturn,",
  "        sharpe: result.sharpe, maxDrawdown: result.maxDrawdown,",
  "        winRate: result.winRate, profitFactor: result.profitFactor,",
  "        tradeCount: result.tradeCount,",
  "      });",
  "",
  "      if (result.totalReturn > (bestResult?.totalReturn || -999)) {",
  "        bestResult = result; bestStrategyName = s;",
  "      }",
  "    } else {",
  "      allDetails.push({",
  "        strategyName: s, status: 'Failed',",
  "        reason: 'No trades generated',",
  "        totalReturn: 0, sharpe: 0, maxDrawdown: 0, winRate: 0, profitFactor: 0, tradeCount: 0, windowUsed: windowUsed,",
  "      });",
  "    }",
  "",
  "    // Delay between strategies",
  "    await new Promise(r => setTimeout(r, 500));",
  "  }",
  "",
  "  // Build overall result from best strategy",
  "  if (!bestResult) {",
  "    const allSkipped = allDetails.filter((d: any) => d.status === 'Skipped').length === allDetails.length;",
  "    return {",
  "      status: 'Error', bestStrategy: 'N/A',",
  "      totalReturn: 0, sharpe: 0, maxDrawdown: 0, winRate: 0, profitFactor: 0, tradeCount: 0, recentValid: false,",
  "      summary: allSkipped ? 'All strategies not supported by backtest engine' : 'Backtest API returned no usable data',",
  "      errorClassification: allSkipped ? 'strategy_not_mapped' : 'api_failed_or_empty',",
  "      details: allDetails,",
  "    };",
  "  }",
  "",
  "  // Overall evaluation (same thresholds, based on best strategy)",
  "  const tc = bestResult.tradeCount; const tr = bestResult.totalReturn;",
  "  const dd = bestResult.maxDrawdown; const sr = bestResult.sharpe; const pf = bestResult.profitFactor;",
  "  let overallStatus = 'Caution';",
  "  const parts: string[] = [];",
  "  if (tc < 3) { overallStatus = 'Failed'; parts.push('insufficient trades (' + tc + ')'); }",
  "  else if (tr < -5) { overallStatus = 'Failed'; parts.push('negative'); }",
  "  else if (dd > 30) { overallStatus = 'Caution'; parts.push('high drawdown ' + dd.toFixed(1) + '%'); }",
  "  else if (sr < 0.5 && tc < 10) { overallStatus = 'Caution'; parts.push('low sharpe ' + sr.toFixed(2)); }",
  "  else if (pf < 0.8 && tc < 15) { overallStatus = 'Caution'; parts.push('PF low ' + pf.toFixed(2)); }",
  "  else { overallStatus = 'Passed'; parts.push('stable'); }",
  "  if (pf >= 1.5) parts.push('PF ' + pf.toFixed(2));",
  "  if (dd > 5) parts.push('MDD ' + dd.toFixed(1) + '%');",
  "  if (sr > 1.0) parts.push('SR ' + sr.toFixed(2));",
  "  if (bestResult.winRate > 0) parts.push('WR ' + bestResult.winRate.toFixed(0) + '%');",
  "",
  "  return {",
  "    status: overallStatus, bestStrategy: bestStrategyName,",
  "    totalReturn: bestResult.totalReturn, sharpe: bestResult.sharpe,",
  "    maxDrawdown: bestResult.maxDrawdown, winRate: bestResult.winRate,",
  "    profitFactor: bestResult.profitFactor, tradeCount: bestResult.tradeCount,",
  "    recentValid: overallStatus === 'Passed',",
  "    summary: parts.join('; '),",
  "    details: allDetails,",
  "  };",
  "};",
];

// Insert before handleRunFineScan (after analyzeMultiTimeframe)
l.splice(newHandleFn, 0, ...runQuickBt);
console.log('Inserted runQuickBacktest. Lines:', l.length);

// ============================
// 4. Modify handleRunFineScan: add MTF + backtest fields, symbol-by-symbol execution
// ============================
// Find key locations inside handleRunFineScan
// The original v1.8.5 handleRunFineScan adds results with specific fields
// We need to find the results.push call

const pushIdx = l.findIndex(x => x.indexOf('results.push') >= 0 && x.indexOf('symbol') >= 0);
console.log('results.push at', (pushIdx+1));
// Show context around it
for (let i = Math.max(0, pushIdx-5); i < pushIdx+35; i++) {
  if (l[i].indexOf('results.push') >= 0 || l[i].indexOf('backtest:') >= 0 || l[i].indexOf('mtf:') >= 0 || l[i].indexOf('conclusion') >= 0 || l[i].indexOf('decisionScore') >= 0) {
    console.log((i+1),':',l[i].trim().substring(0,80));
  }
}

fs.writeFileSync(path, l.join('\n'), 'utf8');
console.log('Phase 1 done. Lines:', l.length);
