if __name__ == "__main__":
    print("================================================================================")
    print("优化版后端启动 - 性能优化 + Analyze修复 + Alpaca Paper Trading + AI Trading")
    print("特性:")
    print("  1. 30秒内存缓存")
    print("  2. 并行API调用")
    print("  3. 限制并发数避免触发API限制")
    print("  4. 响应时间统计")
    print("新增Analyze页面修复:")
    print("  5. /market/history/<symbol> - 历史数据接口 (Twelve Data)")
    print("  6. /market/stock/<symbol> - 股票详情接口")
    print("  7. 间隔映射: 30->30min, 60->1h, D->1day")
    print("新增Backtest页面修复:")
    print("  8. /backtest/run - 运行回测 (Real Data使用Twelve Data真实数据)")
    print("  9. /backtest/history - 获取回测历史")
    print("  10. /backtest/results/<id> - 获取回测结果")
    print("新增Alpaca Paper Trading:")
    print("  11. /api/broker/account - 获取Alpaca账户信息")
    print("  12. /api/broker/positions - 获取Alpaca持仓")
    print("  13. /api/broker/orders - 获取Alpaca订单")
    print("  14. /api/broker/order - 下Alpaca订单")
    print("  15. /api/broker/order/<order_id> - 取消Alpaca订单")
    print("新增AI Trading:")
    print("  16. /api/ai/trade/preview - AI交易预览")
    print("  17. /api/ai/trade/execute - 执行AI交易")
    print("  18. /api/ai/trade/toggle - 切换自动交易模式")
    print("  19. /api/ai/trade/status - 获取AI交易状态")
    print("  20. /api/ai/trade/history - 获取AI交易历史")
    print("新增AI Trading Block 1 & 2:")
    print("  21. /api/ai/provider/config - AI Provider配置")
    print("  22. /api/ai/provider/test - AI Provider连接测试")
    print("  23. /api/ai/trading/environment - Trading环境配置")
    print("  24. /api/ai/alpaca/account - AI专用Alpaca账户接口")
    print("  25. /api/ai/alpaca/positions - AI专用Alpaca持仓接口")
    print("  26. /api/ai/alpaca/orders - AI专用Alpaca订单接口")
    print("  27. /api/ai/alpaca/orders/history - AI专用Alpaca订单历史接口")
    print("新增AI Trading Block 3:")
    print("  28. /api/ai/chat - AI聊天接口")
    print("  29. /api/ai/chat/history - 获取AI聊天历史")
    print("  30. /api/ai/chat/clear - 清空AI聊天历史")
    print("端口: 8889")
    print("================================================================================\n")
    
    app.run(host='127.0.0.1', port=8889, debug=False, use_reloader=False)  # 关闭debug模式提高性能